[package]
name = "indexer-example"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.9"
actix-web = "3"
bson = "1.1.0"
clap = "3.0.0-beta.1"
dotenv = "0.15.0"
openssl-probe = { version = "0.1.2" }
serde_json = "1.0.55"
tokio = { version = "0.2", features = ["sync"] }
tracing-subscriber = "0.2.4"
tokio-diesel = "0.3.0"
diesel = { version = "1.4.5", features = ["chrono", "postgres", "numeric", "serde_json"] }
bigdecimal = "0.1.2"
chrono = "0.4.13"
mongodb = "1.1.1"
near-indexer = { git = "https://github.com/nearprotocol/nearcore", rev="e3cd9fc64df37fbbbb7c44ff27a2ee615356b76c" }
near-store = { git = "https://github.com/nearprotocol/nearcore", rev="e3cd9fc64df37fbbbb7c44ff27a2ee615356b76c" }
near-chain = { git = "https://github.com/nearprotocol/nearcore", rev="e3cd9fc64df37fbbbb7c44ff27a2ee615356b76c" }
neard = { git = "https://github.com/nearprotocol/nearcore", rev="e3cd9fc64df37fbbbb7c44ff27a2ee615356b76c" }
near-chain-configs = { git = "https://github.com/nearprotocol/nearcore", rev="e3cd9fc64df37fbbbb7c44ff27a2ee615356b76c" }
qstring = "0.7.2"
