[package]
name = "indexer-example"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "=0.11.0-beta.2"
actix-web = "=4.0.0-beta.3"
actix-http = "=3.0.0-beta.3"
actix-tls = "=3.0.0-beta.3"
actix_derive = "=0.6.0-beta.1"
funty = "=1.1.0"
bson = "1.1.0"
clap = "3.0.0-beta.1"
dotenv = "0.15.0"
openssl-probe = { version = "0.1.2" }
serde_json = "1.0.55"
<<<<<<< HEAD
tokio = { version = "1.1.1", features = ["sync"] }
tokio-stream = "0.1"
=======
tokio = { version = "1.1", features = ["sync", "time"] }
tokio-stream = { version = "0.1" }
>>>>>>> d1c391c12d1c9ea09b5b59b0181793e525b42b70
tracing-subscriber = "0.2.4"
bigdecimal = "0.1.2"
chrono = "0.4.13"
mongodb = "2.0.0-alpha"
<<<<<<< HEAD
near-indexer = { git = "https://github.com/nearprotocol/nearcore", rev="69eddab7a0d59fd255b71bd6362787f84457c483" }
near-store = { git = "https://github.com/nearprotocol/nearcore", rev="69eddab7a0d59fd255b71bd6362787f84457c483" }
near-chain = { git = "https://github.com/nearprotocol/nearcore", rev="69eddab7a0d59fd255b71bd6362787f84457c483" }
neard = { git = "https://github.com/nearprotocol/nearcore", rev="69eddab7a0d59fd255b71bd6362787f84457c483" }
near-chain-configs = { git = "https://github.com/nearprotocol/nearcore", rev="69eddab7a0d59fd255b71bd6362787f84457c483" }
near-crypto = { git = "https://github.com/nearprotocol/nearcore", rev="69eddab7a0d59fd255b71bd6362787f84457c483" }
qstring = "0.7.2"
=======
near-indexer = { git = "https://github.com/nearprotocol/nearcore", rev="f31cfb954bdd81885bc789bfa406035717db5ab5" }
near-store = { git = "https://github.com/nearprotocol/nearcore", rev="f31cfb954bdd81885bc789bfa406035717db5ab5" }
near-chain = { git = "https://github.com/nearprotocol/nearcore", rev="f31cfb954bdd81885bc789bfa406035717db5ab5" }
neard = { git = "https://github.com/nearprotocol/nearcore", rev="f31cfb954bdd81885bc789bfa406035717db5ab5" }
near-chain-configs = { git = "https://github.com/nearprotocol/nearcore", rev="f31cfb954bdd81885bc789bfa406035717db5ab5" }
near-crypto = { git = "https://github.com/nearprotocol/nearcore", rev="f31cfb954bdd81885bc789bfa406035717db5ab5" }
qstring = "0.7.2"
>>>>>>> d1c391c12d1c9ea09b5b59b0181793e525b42b70
